import Login from '@/components/Login';
import React from 'react';
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "UMS | Login",
  description: "Generated by create next app"
};

const LoginPage = () => {
  
  return (
    <>
       <Login />
    </>
  );
};

export default LoginPage;