import Login from '@/components/Login';
import React from 'react';
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "University Management-Login",
  description: "Generated by create next app"
};

const LoginPage = () => {
  
  return (
    <div>
       <Login />
    </div>
  );
};

export default LoginPage;